working_villages_enable_spawn = false
working_villages_enable_passive_spawn = false
working_villages_gameplay_mode = survival
working_villages_self_employed_public = false
enable_damage = false
creative_mode = false
server_announce = false
max_users = 1
name = wv_owner_alpha
