name = working_villages
title = Working Villages
description = Villageois autonomes en cours de stabilisation pour Minetest Game et VoxeLibre.
depends = 
optional_depends = areas,doors,beds,default,farming,flowers,mcl_core,mcl_doors,mcl_beds,mcl_chests,mcl_farming,mcl_torches,mcl_player,mcl_armor,mcl_skins,mcl_stairs,mcl_furnaces,mcl_fences,mcl_wool,mcl_copper,mcl_tools,mcl_shields,mcl_crafting_table,mcl_inventory,mcl_sounds,mcl_mobs,mcl_books,mcl_mushrooms
